### ISSUE TITLE
Delay between ww recognition and acknowledgement sound

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-dinkum-listener#107]
I've observed, when running OVOS on a Mac, that there's a noticeable delay between the wakeword being recognized and playing the acknowledgement sound. At first it seemed to happen mostly when the chunk_size was increased to huge numbers (accommodating an input buffer overflow in the pyaudio mic plugin). However, when I ran Neon on my Mac, I didn't experience this problem no matter how large or small the chunk_size was.

Neon is pinning ovos-dinkum-listener==0.0.3a16, so something between that version and current alpha is likely the cause of this issue.

**Comment by goldyfruit** [comment]
Do you have `instant_listen` and `confirm_listening` set to `true`, if yes have a look here https://github.com/JarbasHiveMind/HiveMind-core/issues/81

**Comment by mikejgray** [comment]
Not sure, is that the default combo? I know as of Neon's last pinned version of Dinkum it worked, but somewhere between that one and current it stopped working.

**Comment by mikejgray** [comment]
I set `instant_listen` to true and the delay problems went away, whether I had `confirm_listening` on or not. It appears that the issue is isolated to the use case where `instant_listen` is false?

**Comment by JarbasAl** [comment]
`confirm_listening` wait [is skipped](https://github.com/OpenVoiceOS/ovos-dinkum-listener/blob/1e5aa2e312e6686f1fea5bfcea47cc3c553f1779/ovos_dinkum_listener/service.py#L791) if `instant_listen` is set

the problem seems to be something around this event not being set, the delay being the timeout i assume

https://github.com/OpenVoiceOS/ovos-dinkum-listener/blob/1e5aa2e312e6686f1fea5bfcea47cc3c553f1779/ovos_dinkum_listener/voice_loop/voice_loop.py#L182

**Comment by emphasize** [comment]
_Normally_ when the sound is played by the audio subsystem the event is set [here](https://github.com/OpenVoiceOS/ovos-dinkum-listener/blob/1e5aa2e312e6686f1fea5bfcea47cc3c553f1779/ovos_dinkum_listener/service.py#L880) (triggered by the msg type `mycroft.audio.play_sound.response`), otherwise the it is set after .5 secs.
